### ISSUE TITLE
Move to playground 

### ISSUE THREAD

**Issue by f3l1x** [contributte/api-router-project#2]
We should centralize our examples/projects onto 1 repository. WDYT? @paveljanda

**Comment by paveljanda** [comment]
@f3l1x One repository or one other group/org? For example, there are many packages in `contributte` (api-router, application, event-dispatcher, datagrid, ...), so there can be also a `contributte-playground/datagrid`, `contribute-playground/api-router`.

I don't really like putting "sandboxes" of all `contributte` projects into 1 repo.

**Comment by f3l1x** [comment]
Solved. 

PS: I've convinced @paveljanda. Haha ;-)
